### ISSUE TITLE
genesis fetch-kit does not fetch latest version.

### ISSUE THREAD

**Issue by anishp55** [genesis-community/genesis#366] opened 2020-03-19 01:43 UTC
when doing a fetch kit, it only seems to be grabbing 1.9.3

> $ genesis fetch-kit
Attempting to retrieve Genesis kit cf (latest version)...
Downloaded version 1.9.3 of the cf kit

manually fetching the latest kits still works.

**Comment by dennisjbell** [comment] 2020-03-20 04:43
This has been fixed in the upcoming v2.7.0 release of Genesis, for which a RC will be out tonight.

The root cause of this is that Github returns the collections of releases in chronological order, so because 1.9.3 got released after 1.10.1 (as a backport of its changes), even though it has a lower release version, its comes later and thus was the "latest".

**Closed** 2020-03-28 19:04 UTC
